#!/usr/bin/env bash
# ============================================================
# setup.sh — OBSERVER environment setup
#
# Usage:
#   bash setup.sh              # install into current Python (Docker / CI)
#   bash setup.sh --venv       # create isolated venv at ~/.observer/venv
#   bash setup.sh --reinstall  # (with --venv) wipe ~/.observer/venv first
#   bash setup.sh --alias      # (with --venv) add `observer-activate` to ~/.bashrc
#
# Why --venv uses ~/.observer/venv (not ./venv):
#   The venv lives outside the source tree so that replacing the repo
#   (git pull, rsync, etc.) does NOT wipe installed packages.
# ============================================================

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

GREEN=$'\e[92m'; YELLOW=$'\e[93m'; RED=$'\e[91m'; DIM=$'\e[2m'; RESET=$'\e[0m'
ok()   { echo "  ${GREEN}✓${RESET} $*"; }
warn() { echo "  ${YELLOW}!${RESET} $*"; }
fail() { echo "  ${RED}✗${RESET} $*" >&2; exit 1; }

# ── Flags ─────────────────────────────────────────────────────────────
USE_VENV=0
REINSTALL=0
ADD_ALIAS=0
for arg in "$@"; do
    case "$arg" in
        --venv)      USE_VENV=1 ;;
        --reinstall) REINSTALL=1 ;;
        --alias)     ADD_ALIAS=1 ;;
        -h|--help)   sed -n '2,14p' "$0"; exit 0 ;;
        *) echo "${RED}[ERROR]${RESET} Unknown argument: $arg"; exit 1 ;;
    esac
done

OBSERVER_HOME="${HOME}/.observer"
VENV_DIR="${OBSERVER_HOME}/venv"
ACTIVATE_SH="${OBSERVER_HOME}/activate.sh"
REPO_DIR="$(pwd)"

echo "======================================"
echo " OBSERVER — Environment Setup"
echo "======================================"
if [ "$USE_VENV" = "1" ]; then
    echo "  Mode : venv (${VENV_DIR})"
else
    echo "  Mode : direct (current Python)"
fi
echo "  Repo : ${REPO_DIR}"
echo ""

# ── Python version ────────────────────────────────────────────────────
py_ver=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
case "$py_ver" in
    3.1[0-9]|3.2[0-9]) ok "Python $py_ver" ;;
    *) fail "Python $py_ver — observer requires >= 3.10" ;;
esac

# ── Install ───────────────────────────────────────────────────────────
if [ "$USE_VENV" = "1" ]; then
    mkdir -p "${OBSERVER_HOME}"

    if [ "$REINSTALL" = "1" ] && [ -d "${VENV_DIR}" ]; then
        echo "  ${DIM}[--reinstall] removing ${VENV_DIR}...${RESET}"
        rm -rf "${VENV_DIR}"
    fi

    if [ ! -d "${VENV_DIR}" ]; then
        python3 -m venv "${VENV_DIR}"
        ok "venv created at ${VENV_DIR}"
    else
        ok "venv already exists at ${VENV_DIR}"
    fi

    # shellcheck disable=SC1090
    source "${VENV_DIR}/bin/activate"
    pip install --upgrade pip -q
    pip install -e . -q
    ok "observer installed in venv"

    cat > "${ACTIVATE_SH}" <<EOF
# Generated by observer setup.sh — do not edit by hand.
# Source this to activate the observer venv:
#   source ${ACTIVATE_SH}
export OBSERVER_HOME="${OBSERVER_HOME}"
export OBSERVER_REPO="${REPO_DIR}"
# shellcheck disable=SC1091
source "${VENV_DIR}/bin/activate"
EOF
    chmod +x "${ACTIVATE_SH}"
    ok "wrote ${ACTIVATE_SH}"

    if [ "$ADD_ALIAS" = "1" ]; then
        BASHRC="${HOME}/.bashrc"
        MARKER="# --- observer-activate alias ---"
        if grep -qF "${MARKER}" "${BASHRC}" 2>/dev/null; then
            ok "observer-activate alias already in ${BASHRC}"
        else
            {
                echo ""
                echo "${MARKER}"
                echo "alias observer-activate='source ${ACTIVATE_SH}'"
                echo "# --- end observer-activate alias ---"
            } >> "${BASHRC}"
            ok "appended observer-activate alias to ${BASHRC}"
            echo "     Run 'source ${BASHRC}' to pick it up."
        fi
    fi
else
    # Direct install (Docker / CI default)
    if python3 -c 'import eval_runner' 2>/dev/null && command -v observer >/dev/null; then
        ok "observer already installed ($(command -v observer))"
    else
        echo "  ${DIM}pip install -e . ...${RESET}"
        if ! pip install -e . > /tmp/observer-pip.log 2>&1; then
            fail "pip install failed — see /tmp/observer-pip.log"
        fi
        ok "observer installed"
    fi
fi

# ── Environment checks ────────────────────────────────────────────────
echo ""
echo "── Environment ────────────────────────────────────────"

if command -v ffmpeg >/dev/null; then
    ok "ffmpeg in PATH"
else
    warn "ffmpeg not found — sudo apt install ffmpeg (needed for video stage)"
fi

if command -v nvidia-smi >/dev/null; then
    ok "nvidia-smi available"
else
    warn "nvidia-smi not found — CPU-only mode"
fi

if [ -n "${ISAACLAB_PATH:-}" ]; then
    if [ -x "$ISAACLAB_PATH/isaaclab.sh" ]; then
        ok "ISAACLAB_PATH=$ISAACLAB_PATH"
    else
        warn "ISAACLAB_PATH set but $ISAACLAB_PATH/isaaclab.sh is missing"
    fi
else
    warn "ISAACLAB_PATH not set — needed only when video recording is on"
fi

if python3 -c 'import tensorboard' 2>/dev/null; then
    ok "tensorboard installed"
else
    warn "tensorboard not installed — pip install tensorboard (optional)"
fi

echo ""
echo "--------------------------------------"
echo " Done."
echo ""
if [ "$USE_VENV" = "1" ]; then
    echo " Activate (any shell, any directory):"
    echo "   source ~/.observer/activate.sh"
    if [ "$ADD_ALIAS" = "1" ] || grep -qF "observer-activate alias" "${HOME}/.bashrc" 2>/dev/null; then
        echo "   # or:"
        echo "   observer-activate"
    else
        echo ""
        echo " To register a shorter alias, re-run:"
        echo "   bash setup.sh --venv --alias"
    fi
    echo ""
    echo " Reinstall from scratch:"
    echo "   bash setup.sh --venv --reinstall"
else
    echo " Next steps:"
    echo "   1. Edit configs/eval_config.yaml"
    echo "   2. observer doctor"
    echo "   3. make dry DIR=runs/"
fi
echo "--------------------------------------"
