"""
camera_controller.py
====================
Automates Isaac Sim viewport camera movement across predefined pose sequences.

Two usage scenarios:
  A) Imported directly inside an Isaac process (recommended).
  B) Driven by external subprocess camera-switch commands.

Isaac Sim API dependencies:
  - omni.isaac.core.utils.viewports  (legacy viewport, Isaac Sim 2.x/3.x)
  - omni.kit.viewport.utility        (new viewport API, Isaac Sim 4.x+)
"""

from __future__ import annotations
import json
import logging
import math
from pathlib import Path
from typing import Optional

log = logging.getLogger("observer.isaac.camera_controller")

_ISAAC_AVAILABLE = False
try:
    from omni.isaac.core.utils.viewports import set_camera_view
    import omni.kit.viewport.utility as vp_util
    _ISAAC_AVAILABLE = True
    log.info("Isaac Sim viewport API loaded successfully.")
except ImportError:
    log.warning("Isaac Sim API not found — running in mock mode.")


class CameraController:
    """
    Controls the Isaac Sim viewport camera through a sequence of predefined poses.

    Parameters
    ----------
    camera_config_path : str | Path | None
        Path to a camera_poses.json file (generated by PipelineOrchestrator).
    camera_prim_path : str
        USD camera prim path used in the scene.
    """

    def __init__(
        self,
        camera_config_path: Optional[str | Path] = None,
        camera_prim_path: str = "/OmniverseKit_Persp",
    ):
        self.camera_prim_path = camera_prim_path
        self.poses: list[dict] = []
        self._current_idx: int = 0

        if camera_config_path:
            self.load_config(camera_config_path)

    # ── Config loading ────────────────────────────────────────────────
    def load_config(self, path: str | Path):
        """Load camera pose list from a JSON file."""
        with open(path) as f:
            self.poses = json.load(f)
        log.info(f"Loaded {len(self.poses)} camera poses from: {path}")

    def add_pose(
        self,
        name: str,
        eye: list[float],
        target: list[float],
        record_steps: int = 200,
    ):
        """Add a viewpoint at runtime."""
        self.poses.append({
            "name": name,
            "eye": eye,
            "target": target,
            "record_steps": record_steps,
        })

    # ── Camera movement ───────────────────────────────────────────────
    def set_pose(self, pose: dict):
        """Move the Isaac Sim viewport camera to the specified pose."""
        eye    = pose["eye"]
        target = pose["target"]
        name   = pose.get("name", "unnamed")

        log.info(f"  Camera -> [{name}]  eye={eye}  target={target}")

        if _ISAAC_AVAILABLE:
            try:
                viewport = vp_util.get_active_viewport()
                vp_util.set_camera_view(
                    eye=eye,
                    target=target,
                    camera_prim_path=self.camera_prim_path,
                    viewport_api=viewport,
                )
            except Exception:
                # Fallback: legacy API (Isaac Sim 2.x / 3.x)
                set_camera_view(eye=eye, target=target)
        else:
            log.debug(f"  [mock] set_camera_view(eye={eye}, target={target})")

    def set_pose_by_name(self, name: str):
        """Select a viewpoint by name."""
        for pose in self.poses:
            if pose["name"] == name:
                self.set_pose(pose)
                return
        raise ValueError(f"Camera pose '{name}' not found.")

    def set_pose_by_index(self, idx: int):
        """Select a viewpoint by index."""
        if idx < 0 or idx >= len(self.poses):
            raise IndexError(
                f"Camera index {idx} out of range (total: {len(self.poses)})"
            )
        self._current_idx = idx
        self.set_pose(self.poses[idx])

    # ── Automated sweep ───────────────────────────────────────────────
    def sweep(self, on_pose_set_callback=None):
        """
        Iterate through all viewpoints in sequence.

        Parameters
        ----------
        on_pose_set_callback : callable(pose_dict) | None
            Called immediately after each camera move.
            Typically used to trigger recording or run policy steps.
        """
        log.info(f"Starting camera sweep: {len(self.poses)} viewpoints")
        for idx, pose in enumerate(self.poses):
            log.info(f"  [{idx+1}/{len(self.poses)}] {pose['name']}")
            self.set_pose(pose)
            if on_pose_set_callback is not None:
                on_pose_set_callback(pose)
        log.info("Camera sweep complete.")

    # ── Orbital pose generation ───────────────────────────────────────
    @staticmethod
    def generate_orbit_poses(
        target: list[float],
        radius: float = 0.6,
        height: float = 0.4,
        n_steps: int = 8,
        record_steps_each: int = 100,
    ) -> list[dict]:
        """
        Generate a circular orbit around the target point.

        Parameters
        ----------
        target : [x, y, z] look-at point (world frame, meters)
        radius : orbit radius (meters)
        height : camera height above target (meters)
        n_steps : number of orbit stops (8 = 45-degree intervals)
        record_steps_each : simulation steps to record at each stop
        """
        poses = []
        for i in range(n_steps):
            angle = 2 * math.pi * i / n_steps
            eye = [
                target[0] + radius * math.cos(angle),
                target[1] + radius * math.sin(angle),
                target[2] + height,
            ]
            poses.append({
                "name": f"orbit_{i:02d}",
                "eye": [round(v, 4) for v in eye],
                "target": target,
                "record_steps": record_steps_each,
            })
        return poses
